### ISSUE TITLE
Not working since latest update

### ISSUE THREAD

**Issue by jamieasp** [labteral/chatgpt-python#17]
Thanks for the update - excited to try streaming.

Neither .stream nor .chat are working for me since the last update though:

> conversation.chat(query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/replitappname/venv/lib/python3.8/site-packages/chatgpt/chatgpt.py", line 412, in chat
    raise ChatgptError(
chatgpt.errors.ChatgptError: \n

**Comment by dsva97** [comment]
me too
This code:


`
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from chatgpt import Conversation

conversation = Conversation()

for chunk in conversation.stream("We are going to start a conversation. I will speak English and you will speak Portuguese."):
    print(chunk, end="")
    sys.stdout.flush()

print(conversation.chat("What's the color of the sky?"))
`


doing nothing

**Comment by AlexSua** [comment]
The guys from openAI has updated the login mechanism. I think I know how to fix the thing, and I will make an update to address the issue today or tomorrow.

**Comment by MJeremy2017** [comment]
btw, do we support using the API key to login. Guess that's safer and easier for wider adoption.

**Comment by Rainjob** [comment]
OpenAI sure doesn't feel so open.

**Comment by alkollo** [comment]
Got an error, I think it comes from Cloudflare protection 


"

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>77999b74e9781294</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>"

**Comment by kazu-321** [comment]
https://github.com/acheong08/ChatGPT/issues/261

**Comment by gptlang** [comment]
Has this been fixed yet?
