### ISSUE TITLE
Not working with error

### ISSUE THREAD

**Issue by NLGithubWP** [labteral/chatgpt-python#21]
`

Traceback (most recent call last):
  File "/Users/kevin/project_golang/src/github.com/IPM/python/chatgpt_wrapper/chatgptcli.py", line 11, in <module>
    for chunk in conversation.stream("We are going to start a conversation. I will speak English and you will speak Portuguese."):
  File "/Users/kevin/opt/anaconda3/envs/naslibenv/lib/python3.7/site-packages/chatgpt/chatgpt.py", line 267, in stream
    response = self.chat(message, retry_on_401, True, True)
  File "/Users/kevin/opt/anaconda3/envs/naslibenv/lib/python3.7/site-packages/chatgpt/chatgpt.py", line 410, in chat
    return self.chat(message, False, direct_response=direct_response, stream=stream)
  File "/Users/kevin/opt/anaconda3/envs/naslibenv/lib/python3.7/site-packages/chatgpt/chatgpt.py", line 421, in chat
    exception_message, exception_code)
chatgpt.errors.ChatgptError: Login error. Try again or use interceptor.js as explained in the documentation.
`

**Comment by Kazu-School** [comment]
https://github.com/acheong08/ChatGPT/issues/261
when you login, chatgpt use cloudflare.
