### ISSUE TITLE
unable to login? offer to use  interceptor.js?

### ISSUE THREAD

**Issue by githubbla** [labteral/chatgpt-python#25]
% chatgpt
> summary 500 words about israel
> ERROR: Login error. Try again or use interceptor.js as explained in the documentation.
> exit

**Comment by matteoferla** [comment]
The issue #1 has the same error, albeit older, but with more details.
Logging in on browser gives the Google Captcha (click on motorbikes, signs, mountains, drug dealers, traffic lights etc.).
The json response of `/session` in the browser has a `access_token`, while the request in `/conversation` (question asked by user) has the `conversation_id` and `parent_message_id` values. However, using these gives an ChatGTPError message `\n`.

**Comment by githubbla** [comment]
> The issue #1 has the same error, albeit older, but with more details. Logging in on browser gives the Google Captcha (click on motorbikes, signs, mountains, drug dealers, traffic lights etc.). The json response of `/session` in the browser has a `access_token`, while the request in `/conversation` (question asked by user) has the `conversation_id` and `parent_message_id` values. However, using these gives an ChatGTPError message `\n`.

thank you for point me for this access_token auth way.
After i fill the access_token and the rest getting without error, but not result.

% chatgpt       
> hello man!
> ERROR: \n        
> how are you?
> ERROR: \n        
> %                            


 % python3 test.py
Traceback (most recent call last):
  File "/Users/roman/Projects/claw.games/texts/test.py", line 9, in <module>
    for chunk in conversation.stream("We are going to start a conversation. I will speak English and you will speak Portuguese."):
  File "/usr/local/lib/python3.10/site-packages/chatgpt/chatgpt.py", line 267, in stream
    response = self.chat(message, retry_on_401, True, True)
  File "/usr/local/lib/python3.10/site-packages/chatgpt/chatgpt.py", line 420, in chat
    raise ChatgptError(
chatgpt.errors.ChatgptError: \n

**Comment by andreacortis** [comment]
same error here, 
1. I tried to login with my google account credentials and got an error
2. I do have an openAI token, but (a) I am not sure that is the one that is needed, (b) nor where to provide that token in the char request

**Comment by chrischma** [comment]
> % chatgpt
> 
> > summary 500 words about israel
> > ERROR: Login error. Try again or use interceptor.js as explained in the documentation.
> > exit

same here...
where exactly can i find information about interceptor.js?
